### ISSUE TITLE
Unable to start image due to an options error

### ISSUE THREAD

**Issue by Demon-tk** [monstrenyatko/docker-openvpn-client#1]
I receive the error: `Options error: You must define TUN/TAP device (--dev)`

Am I missing something? My `/dev/net:/dev/net` looks correct. 

```yml
version: '3'
services:
  openvpn-client:
    image: monstrenyatko/openvpn-client
    container_name: openvpn-client
    environment:
      - NET_LOCAL
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /dev/net:/dev/net:z
      - ./config:/config/client.ovpn:ro
    ports:
    # some service web interface
     - "8000:8000"
     - "25565:25565"
     ```
